### Patient Signup
POST http://localhost:3005/api/auth/signup
Content-Type: application/json

{
  "name": "Tejas",
  "email": "sanju12@example.com",
  "phone": "9876543210",
  "password": "test1234"
}
